# Generated by Django 4.0.4 on 2023-03-03 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='massage',
            new_name='message',
        ),
    ]
