# Generated by Django 4.0.4 on 2023-03-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_visted_site_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='email',
            name='created_at',
            field=models.DateTimeField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visted_site',
            name='created_at',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
